GET http://localhost:8080/user/getAll

###

GET http://localhost:8080/user/getByLogin?login=test2

###

POST http://localhost:8080/home/reg
Content-Type: application/json

{
  "name": "Test1",
  "login": "test1",
  "password": "111"
}

###

GET http://localhost:8080/home/auth?login=test1&password=111
token: 1jFI8_35JTA7h5Y5kcVo8PRs1IC8HuYZ

###